sudo: required
addons:
  apt:
    update: true
language: scala
branches:
  only:
    - master
    - /^v\d+(\.\d+)+$/
before_install:
  - curl https://raw.githubusercontent.com/scala-native/scala-native/v0.3.7/scripts/travis_setup.sh | bash -x
install:
  - pyenv global 3.6
  - pip install jep
script:
  - export JEP_PATH="/opt/python/3.6.3/lib/python3.6/site-packages/jep"
  - sbt test
after_success:
  - 'if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./publish.sh; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ -n "$TRAVIS_TAG" ]; then bash ./publish.sh; fi'
