sudo: required
addons:
  apt:
    update: true
language: scala
branches:
  only:
    - master
    - /^v\d+(\.\d+)+$/
before_install:
  - curl https://raw.githubusercontent.com/scala-native/scala-native/v0.3.7/scripts/travis_setup.sh | bash -x
install:
  - pyenv install -s 3.6.3
  - pyenv global 3.6.3
script:
  - export LD_LIBRARY_PATH=$(python3-config --prefix)/lib
  - sbt test
after_success:
  - 'if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./publish.sh; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ -n "$TRAVIS_TAG" ]; then bash ./publish.sh; fi'
